window.AppConfig = {
  SQLITE_WASM_URL: '/js/vendor/sqlite-wasm/index.mjs',
  WORD_ANNOTATIONS_V2_ENABLED: true,
  STUDY_ASSET_BASE_URL: 'https://repo.focusedword.com/study',
  WORD_ANNOTATIONS_V2_DB: 'https://repo.focusedword.com/study/BSB_token_annotations_v2.sqlite',
  WORD_ANNOTATIONS_V2_MANIFEST: 'https://repo.focusedword.com/study/BSB_token_annotations_v2.sqlite.manifest.json',
  WORD_ANNOTATIONS_V2_VOCABULARY: 'https://repo.focusedword.com/study/BSB_token_annotations_v2.vocabulary.json',
  WORD_STUDY_DATA_DB: 'https://repo.focusedword.com/study/bsb_word_data.sqlite',
  LEXICON_DATA_DB: 'https://repo.focusedword.com/study/lexicon_data.sqlite',
  DEFAULT_PORT: 3000,
  MAX_CHAPTER_NAV_LOCK: 800,
  MIN_CHAPTER_NAV_LOCK: 600,
  POINTER_TAP_THRESHOLD: 150,
  POINTER_GRACE_PERIOD: 150,
  POINTER_CLEAR_DELAY: 300,
  SCROLL_BOTTOM_WEIGHT_START: 0.88,
  SCROLL_BOTTOM_WEIGHT_END: 0.12,
  SPEED_ORP_RATIO: 0.35,
  CROSSREF_MAX_DISPLAY: 3,
  CROSSREF_MIN_VOTES: 2,
  SWIPE_MAX_VERSE_MEASURE: 500,
  SEARCH_MAX_LENGTH: 200,
};
